[package]
name = "es_logger"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0"
common = { path = "../common" }
<<<<<<< Updated upstream
base64 = "0.22"
=======
base64 = "0.22"
chrono = "0.4"
>>>>>>> Stashed changes
